DTEMRegistries = DTEMRegistries or {}
DTEMRegistries.CharacterTrait = DTEMRegistries.CharacterTrait or {}

local function registerTrait(key, resourceName)
    if CharacterTrait and CharacterTrait.register then
        DTEMRegistries.CharacterTrait[key] = CharacterTrait.register(resourceName)
    end
end

-- Build 42 loads registries before script definitions. These ids must match
-- media/scripts/generated/characters/dtem_character_traits.txt and old saves.
registerTrait("addictedtocaffeine", "base:addictedtocaffeine")
registerTrait("alcoholic", "base:alcoholic")
registerTrait("amateurelectrician", "base:amateurelectrician")
registerTrait("amateurelectrician2", "base:amateurelectrician2")
registerTrait("amcarpenter", "base:amcarpenter")
registerTrait("amcook", "base:amcook")
registerTrait("amelectrician", "base:amelectrician")
registerTrait("amforager", "base:amforager")
registerTrait("ammechanic", "base:ammechanic")
registerTrait("ammetalworker", "base:ammetalworker")
registerTrait("amtrapper", "base:amtrapper")
registerTrait("anorexy", "base:anorexy")
registerTrait("bigorexia", "base:bigorexia")
registerTrait("bloodlust", "base:bloodlust")
registerTrait("brittleknees", "base:brittleknees")
registerTrait("cutter", "base:cutter")
registerTrait("dextrous2", "base:dextrous2")
registerTrait("durabile", "base:durabile")
registerTrait("fibromyalgia", "base:fibromyalgia")
registerTrait("flabby", "base:flabby")
registerTrait("flimsy", "base:flimsy")
registerTrait("frail", "base:frail")
registerTrait("gunfan", "base:gunfan")
registerTrait("handy2", "base:handy2")
registerTrait("herbalist2", "base:herbalist2")
registerTrait("lightfooted", "base:lightfooted")
registerTrait("lucky", "base:lucky")
registerTrait("melancholic", "base:melancholic")
registerTrait("nervouswreck", "base:nervouswreck")
registerTrait("nightmares", "base:nightmares")
registerTrait("nimble", "base:nimble")
registerTrait("physicallyactive", "base:physicallyactive")
registerTrait("physicallyactive2", "base:physicallyactive2")
registerTrait("pillsallergy", "base:pillsallergy")
registerTrait("pluviophile", "base:pluviophile")
registerTrait("pluviophobia", "base:pluviophobia")
registerTrait("poorpassenger", "base:poorpassenger")
registerTrait("prodigy", "base:prodigy")
registerTrait("sedentary", "base:sedentary")
registerTrait("shortbladefan", "base:shortbladefan")
registerTrait("shortbluntfan", "base:shortbluntfan")
registerTrait("sneaky", "base:sneaky")
registerTrait("spearman", "base:spearman")
registerTrait("swordsman", "base:swordsman")
registerTrait("unlucky", "base:unlucky")
registerTrait("wildplantsallergy", "base:wildplantsallergy")
