DTEMRegistries = DTEMRegistries or {}
DTEMRegistries.CharacterTrait = DTEMRegistries.CharacterTrait or {}

local function registerTrait(key, resourceName)
    if CharacterTrait and CharacterTrait.register then
        DTEMRegistries.CharacterTrait[key] = CharacterTrait.register(resourceName)
    end
end

-- Build 42 loads registries before script definitions. Mod traits must live
-- outside the reserved base namespace and match script resource ids below.
registerTrait("addictedtocaffeine", "DynamicTraits:addictedtocaffeine")
registerTrait("alcoholic", "DynamicTraits:alcoholic")
registerTrait("amateurelectrician", "DynamicTraits:amateurelectrician")
registerTrait("amateurelectrician2", "DynamicTraits:amateurelectrician2")
registerTrait("amcarpenter", "DynamicTraits:amcarpenter")
registerTrait("amcook", "DynamicTraits:amcook")
registerTrait("amelectrician", "DynamicTraits:amelectrician")
registerTrait("amforager", "DynamicTraits:amforager")
registerTrait("ammechanic", "DynamicTraits:ammechanic")
registerTrait("ammetalworker", "DynamicTraits:ammetalworker")
registerTrait("amtrapper", "DynamicTraits:amtrapper")
registerTrait("anorexy", "DynamicTraits:anorexy")
registerTrait("bigorexia", "DynamicTraits:bigorexia")
registerTrait("bloodlust", "DynamicTraits:bloodlust")
registerTrait("brittleknees", "DynamicTraits:brittleknees")
registerTrait("cutter", "DynamicTraits:cutter")
registerTrait("dextrous2", "DynamicTraits:dextrous2")
registerTrait("durabile", "DynamicTraits:durabile")
registerTrait("fibromyalgia", "DynamicTraits:fibromyalgia")
registerTrait("flabby", "DynamicTraits:flabby")
registerTrait("flimsy", "DynamicTraits:flimsy")
registerTrait("frail", "DynamicTraits:frail")
registerTrait("gunfan", "DynamicTraits:gunfan")
registerTrait("handy2", "DynamicTraits:handy2")
registerTrait("herbalist2", "DynamicTraits:herbalist2")
registerTrait("lightfooted", "DynamicTraits:lightfooted")
registerTrait("lucky", "DynamicTraits:lucky")
registerTrait("melancholic", "DynamicTraits:melancholic")
registerTrait("nervouswreck", "DynamicTraits:nervouswreck")
registerTrait("nightmares", "DynamicTraits:nightmares")
registerTrait("nimble", "DynamicTraits:nimble")
registerTrait("physicallyactive", "DynamicTraits:physicallyactive")
registerTrait("physicallyactive2", "DynamicTraits:physicallyactive2")
registerTrait("pillsallergy", "DynamicTraits:pillsallergy")
registerTrait("pluviophile", "DynamicTraits:pluviophile")
registerTrait("pluviophobia", "DynamicTraits:pluviophobia")
registerTrait("poorpassenger", "DynamicTraits:poorpassenger")
registerTrait("prodigy", "DynamicTraits:prodigy")
registerTrait("sedentary", "DynamicTraits:sedentary")
registerTrait("shortbladefan", "DynamicTraits:shortbladefan")
registerTrait("shortbluntfan", "DynamicTraits:shortbluntfan")
registerTrait("sneaky", "DynamicTraits:sneaky")
registerTrait("spearman", "DynamicTraits:spearman")
registerTrait("swordsman", "DynamicTraits:swordsman")
registerTrait("unlucky", "DynamicTraits:unlucky")
registerTrait("wildplantsallergy", "DynamicTraits:wildplantsallergy")
